version: '3'
services:
  api:
    image: api:user_task
    container_name: api-user_task
    build:
      context: ./
      dockerfile: api.Dockerfile
      target: runner
    restart: always
    ports:
      - "8081:8081"
    networks:
      - local-network-user_task

  mysql_db_user_task:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=user_task
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=52000
    ports:
      - '52000:52000'
    networks:
      - local-network-user_task

networks:
  local-network-user_task:
    driver: bridge